smtCommunityTimelineBox:
  caption:
    ja_JP: "コミュニティタイムライン"
    en_US: "Community timeline"
  description:
    ja_JP: "コミュニティのタイムラインを表示します。"
    en_US: "The timeline of a community is displayed."
  component: [timeline, smtTimelineCommunity]
  config:
    limit:
      Name:      "limit"
      Caption:   "最大表示件数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    20
      Choices:
        5: 5
        10: 10
        15: 15
        20: 20

smtCommunityTimelineBy1:
  caption:
    ja_JP: "コミュニティのタイムライン(1行表示)"
    en_US: "Timeline of a community (one-line display)"
  description:
    ja_JP: "コミュニティのタイムラインが1行だけ表示されます。"
    en_US: "The timeline of only one line of a community is displayed."
  component: [timeline, smtCommunityTimelineBy1]
